# Generated by Django 6.0.7 on 2026-07-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_player_alter_visitor_ip_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
